from __future__ import annotations

from eidolon.workspaces.workspace_support_projection import project_to_workspace
from eidolon.workspaces.workspace_support_summary import next_actions_from_project, project_summary, workspace_state_from_project
