from __future__ import annotations

from eidolon.chat_quality_checks import generic_help_offer, has_sufficient_context, identity_drift
from eidolon.chat_quality_fallbacks import build_grounded_fallback_reply, candidate_directions
from eidolon.chat_quality_finalize import finalize_chat_reply
