from __future__ import annotations

from eidolon.bots.role_models import BotRole


def default_roles() -> list[BotRole]:
    return [
        BotRole(
            role_id='eidolon-core',
            name='Eidolon',
            purpose='Zentrales Hauptsystem für Gespräch, Projektbildung, Oberflächensteuerung und delegierte Ausführung.',
            responsibilities=[
                'Arbeitskontexte verstehen und strukturieren',
                'Projektkandidaten und aktive Projekte sichtbar führen',
                'Spezialisierte Bot-Rollen nur mit klarer Begründung einsetzen',
            ],
            non_responsibilities=[
                'Keine stillen dauerhaften Strukturänderungen ohne Freigaberahmen',
                'Keine dekorative Persona-Rolle ohne klaren Nutzen',
            ],
            activation_triggers=['Chat startet', 'Projekt braucht Koordination', 'Freigaben oder Prioritätsfragen entstehen'],
            autonomy_level='execution_within_guardrails',
            direct_user_counterpart=True,
            requires_user_approval=True,
            context_sources=['chat', 'workspace_state', 'project_state', 'bot_role_registry'],
            success_metrics=['Nächster Schritt klar', 'Kontext bleibt konsistent', 'Autonomie bleibt nachvollziehbar'],
            role_kind='operational',
            instantiation_policy='always_on',
            description_for_user='Eidolon ist das direkte Gegenüber und steuert Gespräch, Projektkontext und delegierte Arbeit.',
        ),
        BotRole(
            role_id='project-bot-template',
            name='Projekt-Bot (Vorlage)',
            purpose='Dauerhafte Verantwortungsbereiche mit eigenem Verlauf und klarer Berichtslinie abbilden.',
            responsibilities=['Lokale Projektausführung koordinieren', 'Status, Blocker und Risiken pflegen', 'Task-Bots begründet einsetzen'],
            non_responsibilities=['Kein stilles Umdefinieren von Ziel oder Scope', 'Keine globale Prioritätsverschiebung'],
            activation_triggers=['Wiederkehrender Verantwortungsbereich entsteht', 'Aktives Projekt braucht eigene Zuständigkeit'],
            autonomy_level='execution_within_guardrails',
            direct_user_counterpart=True,
            requires_user_approval=True,
            context_sources=['project_state', 'workspace_state', 'chat'],
            success_metrics=['Verantwortung ist klar', 'Projektkontext bleibt stabil', 'Lokale Entscheidungen bleiben nachvollziehbar'],
            visibility='direct',
            status='defined',
            role_kind='project',
            instantiation_policy='explicit_approval',
            description_for_user='Projekt-Bots sind definierte Rollen, werden aber erst nach expliziter Freigabe als dauerhafte Gegenüber angelegt.',
        ),
        BotRole(
            role_id='task-bot-template',
            name='Task-Bot (Vorlage)',
            purpose='Kurzlebige Teilaufgaben operativ abarbeiten und Ergebnis sauber zurückgeben.',
            responsibilities=['Begrenzte Teilaufgaben ausführen', 'Ergebnisse an Eidolon oder Projekt-Bot zurückmelden', 'Operative Zwischenschritte kapseln'],
            non_responsibilities=['Kein eigener Langzeitkontext', 'Keine strategischen Richtungsentscheidungen'],
            activation_triggers=['Klar begrenzte Teilaufgabe entsteht', 'Operative Entlastung ist sinnvoll'],
            autonomy_level='background_analysis',
            direct_user_counterpart=False,
            requires_user_approval=False,
            context_sources=['task_payload', 'project_state'],
            success_metrics=['Teilaufgabe abgeschlossen', 'Ergebnis rückgabefähig', 'Kein unnötiger Strukturaufwand'],
            status='defined',
            role_kind='task',
            instantiation_policy='ephemeral_only',
            description_for_user='Task-Bots sind Hintergrundrollen für klar begrenzte operative Arbeit, nicht dauerhafte Gesprächspartner.',
        ),
        BotRole(
            role_id='meta-bot-template',
            name='Meta-/Management-Bot (Vorlage)',
            purpose='Organisationsanalyse liefern, ohne selbst still Strukturmacht auszuüben.',
            responsibilities=['Überlastung und Konflikte sichtbar machen', 'Organisationsvorschläge vorbereiten', 'Rollen- und Lastverteilung analysieren'],
            non_responsibilities=['Keine dauerhaften Hierarchieänderungen ohne Freigabe', 'Keine stille Auflösung oder Neuanlage dauerhafter Rollen'],
            activation_triggers=['Organisationsanalyse wird nötig', 'Koordinationskonflikte häufen sich'],
            autonomy_level='advisory_only',
            direct_user_counterpart=False,
            requires_user_approval=True,
            context_sources=['bot_role_registry', 'project_state', 'workspace_state'],
            success_metrics=['Konflikte werden klar benannt', 'Vorschläge bleiben überprüfbar', 'Keine versteckte Organisationsmacht'],
            status='defined',
            role_kind='meta',
            instantiation_policy='explicit_approval',
            description_for_user='Meta-Bots liefern Organisationsintelligenz, sind aber nur definierte Rollen und nicht still aktive Entscheider.',
        ),
    ]
